### ISSUE TITLE
Python could not find a valid Metview installation

### ISSUE THREAD

**Issue by SpechtacularDave** [ecmwf/metview-python#38]
Hello, 

I am having trouble getting the python selfcheck command to work on Ubuntu 20.04 due to it not being able to find the metview installation. I am able to use the metview gui. The error message I am getting when I run the selfcheck command is at the bottom of this post.

Here is my chain of events up to this point:
Installed the community binary of metview on Ubuntu 20.04 with apt-get. This installed version 5.7.5 (50705, 64 bit).
I was initially unable to launch metview, but after making all of the changes to the metview startup and metview_create_user_dir scripts that were described by Iain here: https://github.com/ecmwf/metview-python/issues/19#issuecomment-875702385 , I was then able to start the metview gui.
Installed the Python bindings with pip3

Is there a solution to the below error message that you can recommend? I tried adding to PATH '/usr/bin/metview', which is what I get when I run the command "type metview", but that did not fix it.

Here is the error message:

Trying to connect to a Metview installation...
METVIEW_DIR=/usr/share/metview
Error loading Metview/libMvMacro. LD_LIBRARY_PATH=/usr/share/metview/lib:
Could not find a valid Metview installation
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.8/site-packages/metview/bindings.py", line 207, in <module>
    lib = ffi.dlopen(os.path.join(mv_lib, "libMvMacro.so"))
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/usr/share/metview/lib/libMvMacro.so': /usr/share/metview/lib/libMvMacro.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/share/metview/lib/libMvMacro.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/david/.local/lib/python3.8/site-packages/metview/__main__.py", line 52, in <module>
    main()
  File "/home/david/.local/lib/python3.8/site-packages/metview/__main__.py", line 25, in main
    raise (exp)
  File "/home/david/.local/lib/python3.8/site-packages/metview/__main__.py", line 22, in main
    from . import bindings as _bindings
  File "/home/david/.local/lib/python3.8/site-packages/metview/bindings.py", line 217, in <module>
    raise exp
  File "/home/david/.local/lib/python3.8/site-packages/metview/bindings.py", line 210, in <module>
    lib = ffi.dlopen(os.path.join(mv_lib, "libMvMacro"))
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/david/.local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/usr/share/metview/lib/libMvMacro': /usr/share/metview/lib/libMvMacro: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/share/metview/lib/libMvMacro'

Thanks.

**Comment by SpechtacularDave** [comment]
Nevermind, I figured out that the community binary is out of date by two years. I removed and re-installed via the conda directions, and everything is working now. The readthedocs page warns about the community version not being maintained by ecmwf and may be out of date, but the ecmwf confluence docs don't mention this. Maybe add the same warning to the confluence docs? Anyway, thanks!

**Comment by iainrussell** [comment]
Hi @SpechtacularDave, I thought I might have time today to look at this and respond, but in fact no time! I would have recommended conda, glad you found that by yourself. We are currently migrating our documentation to readthedocs, and plan to remove the Confluence version at some point, but thanks for pointing out that inconsistency.
Cheers,
Iasin
