### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by Liar-man** [ecmwf/metview-python#54]
### What happened?

When I followed the instructions to set up metview, I encountered this error during the import process. I have spent a long time searching online for a solution but have not found one yet.

Traceback (most recent call last):
  File "D:\code\python\pythonProject\Wam_Glo\metview-python-master\metview\plotting.py", line 18, in <module>
    import metview as mv
  File "D:\code\python\pythonProject\venv\Lib\site-packages\metview\__init__.py", line 44, in <module>
    raise exp
  File "D:\code\python\pythonProject\venv\Lib\site-packages\metview\__init__.py", line 28, in <module>
    from . import bindings as _bindings
  File "D:\code\python\pythonProject\venv\Lib\site-packages\metview\bindings.py", line 196, in <module>
    mi = MetviewInvoker()
         ^^^^^^^^^^^^^^^^
  File "D:\code\python\pythonProject\venv\Lib\site-packages\metview\bindings.py", line 87, in __init__
    signal.signal(signal.SIGUSR1, self.signal_from_metview)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGUSR1'

### What are the steps to reproduce the bug?

import metview as mv

### Version

1.15 , the latest one

### Platform (OS and architecture)

windows

**Comment by iainrussell** [comment]
Hello @Liar-man, I'm afraid that Metview does not run on Windows. There are two components - the binaries and the Python bindings (which depend on the binaries). You have the Python bindings, but the binaries do not exist for Windows, and we have no plans to make them available (Metview was built for UNIX operating systems).
